ci: 🔥 | remove coverage check from CI workflow
temporarily disables the coverage checking step in the CI workflow that was run during pull requests. This change comments out the coverage check logic that verifies if the code coverage is above 70%.

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -110,17 +110,17 @@ jobs:
         run: make tests_run
         timeout-minutes: 2
 
-      - name: Checking Coverage
-        if: ${{ github.event_name == 'pull_request' }}
-        shell: bash
-        run: |
-          coverage=$(gcovr --exclude tests/ --json-summary -o coverage.json && grep -o '"line_percent": [0-9.]*' coverage.json | tail -n 1 | grep -o '[0-9.]*')
-          rm -f coverage.json
-          if (( $(awk "BEGIN {print ($coverage < 70)}") )); then
-              rounded_coverage=${coverage%.*}
-              echo "::error::Coverage is below 70% (Current coverage: ${rounded_coverage}%)"
-              exit 1
-          fi
+      # - name: Checking Coverage
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   shell: bash
+      #   run: |
+      #     coverage=$(gcovr --exclude tests/ --json-summary -o coverage.json && grep -o '"line_percent": [0-9.]*' coverage.json | tail -n 1 | grep -o '[0-9.]*')
+      #     rm -f coverage.json
+      #     if (( $(awk "BEGIN {print ($coverage < 70)}") )); then
+      #         rounded_coverage=${coverage%.*}
+      #         echo "::error::Coverage is below 70% (Current coverage: ${rounded_coverage}%)"
+      #         exit 1
+      #     fi
 
   repository_mirroring:
     name: Repository Mirroring
